pipeline {
    agent any

    environment {
        IMAGE_NAME = 'chatapi-app-local'
        CONTAINER_NAME = 'chatapi_app'
    }

    stages {
        stage('Run Tests') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    pytest tests/
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Deploy Locally') {
            steps {
                sh '''
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true
                    docker run -d --name $CONTAINER_NAME -p 8000:8000 $IMAGE_NAME
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
